export const colorDescriptions: Record<string, Record<string, string>> = {
  background: {
    primary: "Main background color for windows and editors",
    secondary: "Secondary background for sidebars and panels",
    tertiary: "Lightest background variant for subtle differences",
    selection: "Text selection and highlight background",
    surface: "Floating surfaces like popups and modals",
    overlay: "Overlays and border colors",
    prompt: "Command prompt and input backgrounds",
  },
  foreground: {
    primary: "Main text color",
    secondary: "Secondary text for less important content",
    muted: "Muted text for disabled or inactive elements",
    subtle: "Subtle text for hints and placeholders",
  },
  accent: {
    red: "Red accent for errors and important alerts",
    orange: "Orange accent for warnings",
    yellow: "Yellow accent for highlights",
    green: "Green accent for success and confirmations",
    cyan: "Cyan accent for info and links",
    blue: "Blue accent for primary actions",
    purple: "Purple accent for special elements",
    pink: "Pink accent for decorative elements",
  },
  semantic: {
    error: "Error messages and indicators",
    warning: "Warning messages and alerts",
    success: "Success states and confirmations",
    info: "Informational messages",
    keyword: "Programming language keywords",
    command: "Shell commands and actions",
    operator: "Mathematical and logical operators",
    comment: "Code comments and documentation",
    string: "String literals in code",
    function: "Function names and declarations",
    type: "Data types and class names",
    number: "Numeric literals and constants",
    boolean: "Boolean values (true/false)",
    variable: "Variable names and identifiers",
    property: "Object properties and attributes",
    method: "Method calls and built-in functions",
  },
  terminal: {
    black: "Terminal black",
    red: "Terminal red",
    green: "Terminal green",
    yellow: "Terminal yellow",
    blue: "Terminal blue",
    magenta: "Terminal magenta",
    cyan: "Terminal cyan",
    white: "Terminal white",
    bright_black: "Terminal bright black",
    bright_red: "Terminal bright red",
    bright_green: "Terminal bright green",
    bright_yellow: "Terminal bright yellow",
    bright_blue: "Terminal bright blue",
    bright_magenta: "Terminal bright magenta",
    bright_cyan: "Terminal bright cyan",
    bright_white: "Terminal bright white",
  },
  highlights: {
    low: "Low intensity highlight",
    medium: "Medium intensity highlight",
    high: "High intensity highlight",
  },
};