/* Generated by theme system - DO NOT EDIT DIRECTLY */
/* Theme: ${SCHEME} */

/* Base16 color definitions using @define-color */
@define-color base00 #${BASE00};
@define-color base01 #${BASE01};
@define-color base02 #${BASE02};
@define-color base03 #${BASE03};
@define-color base04 #${BASE04};
@define-color base05 #${BASE05};
@define-color base06 #${BASE06};
@define-color base07 #${BASE07};
@define-color base08 #${BASE08};
@define-color base09 #${BASE09};
@define-color base0A #${BASE0A};
@define-color base0B #${BASE0B};
@define-color base0C #${BASE0C};
@define-color base0D #${BASE0D};
@define-color base0E #${BASE0E};
@define-color base0F #${BASE0F};

/* General colors */
@define-color background #${BACKGROUND};
@define-color foreground #${FOREGROUND};
@define-color foreground-bright #${FOREGROUND_BRIGHT};

/* Waybar window */
@define-color waybar-bg ${WAYBAR_BG};
@define-color waybar-fg #${WAYBAR_FG};

/* Module backgrounds */
@define-color module-bg #${MODULE_BG};

/* Workspace colors */
@define-color workspace-fg #${WAYBAR_WORKSPACE_FG};
@define-color workspace-focused #${WAYBAR_WORKSPACE_FOCUSED};
@define-color workspace-active #${WAYBAR_WORKSPACE_ACTIVE};
@define-color workspace-urgent #${WAYBAR_WORKSPACE_URGENT};
@define-color workspace-hover alpha(#${WAYBAR_WORKSPACE_HOVER}, 0.2);

/* State colors */
@define-color critical #${CRITICAL};
@define-color warning #${WARNING};
@define-color success #${SUCCESS};
@define-color info #${INFO};

/* Battery colors */
@define-color battery-critical #${BATTERY_CRITICAL};
@define-color battery-animation-bg1 alpha(#${BATTERY_ANIMATION_BG1}, 0.5);
@define-color battery-animation-bg2 alpha(#${BATTERY_ANIMATION_BG2}, 0.7);

/* Power profiles colors */
@define-color power-performance #${POWER_PERFORMANCE};
@define-color power-balanced #${POWER_BALANCED};
@define-color power-saver #${POWER_SAVER};
@define-color power-saver-fg #${POWER_SAVER_FG};

/* CPU colors */
@define-color cpu-bg #${CPU_BG};
@define-color cpu-fg #${CPU_FG};

/* Memory colors */
@define-color memory-bg #${MEMORY_BG};

/* Disk colors */
@define-color disk-bg #${DISK_BG};

/* Temperature colors */
@define-color temperature-bg #${TEMPERATURE_BG};
@define-color temperature-critical #${TEMPERATURE_CRITICAL};

/* Tray colors */
@define-color tray-bg #${TRAY_BG};

/* Pulseaudio colors */
@define-color pulseaudio-hover #${PULSEAUDIO_HOVER};
@define-color pulseaudio-muted #${PULSEAUDIO_MUTED};

/* Wireplumber colors */
@define-color wireplumber-bg #${WIREPLUMBER_BG};
@define-color wireplumber-fg #${WIREPLUMBER_FG};
@define-color wireplumber-muted #${WIREPLUMBER_MUTED};

/* Media colors */
@define-color media-bg #${MEDIA_BG};
@define-color media-fg #${MEDIA_FG};
@define-color media-vlc #${MEDIA_VLC};

/* Idle inhibitor colors */
@define-color idle-inhibitor-bg #${IDLE_INHIBITOR_BG};
@define-color idle-inhibitor-active-bg #${IDLE_INHIBITOR_ACTIVE_BG};
@define-color idle-inhibitor-active-fg #${IDLE_INHIBITOR_ACTIVE_FG};

/* MPD colors */
@define-color mpd-bg #${MPD_BG};
@define-color mpd-fg #${MPD_FG};
@define-color mpd-disconnected #${MPD_DISCONNECTED};
@define-color mpd-stopped #${MPD_STOPPED};
@define-color mpd-paused #${MPD_PAUSED};

/* Keyboard state colors */
@define-color keyboard-state-bg #${KEYBOARD_STATE_BG};
@define-color keyboard-state-fg #${KEYBOARD_STATE_FG};

/* Privacy colors */
@define-color privacy-screenshare #${PRIVACY_SCREENSHARE};
@define-color privacy-audio-in #${PRIVACY_AUDIO_IN};
@define-color privacy-audio-out #${PRIVACY_AUDIO_OUT};

/* Tooltip colors */
@define-color tooltip-bg alpha(#${TOOLTIP_BG}, 0.95);